### ISSUE TITLE
thank you :)

### ISSUE THREAD

**Issue by benavern** [sterlingw/Nat-Geo-Photo-of-the-Day-API#1]
Hi, 
This is not an issue, but I want to tell you thank you !
I am still a begginer in web developpement. I was just looking for an images api today just to try something and found yours.
you can check my fresh blog-post here.
http://benavern.github.io/2015/05/06/Labo-National-Geo.html

thank you again and tell me if you want me not to use it anymore or anything else.
(I apologise for my english, frensh student still at school.)

keep hacking ;)

**Comment by sterlingw** [comment]
Hi benavern!

I'm glad you found the API useful! The code is open source - you're free to
do what you'd like with it.

On Wed, May 6, 2015 at 10:50 AM, Benjamin CARADEUC <notifications@github.com
